include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    always_use_package_imports: error
    avoid_empty_else: error

linter:
  rules:
    - camel_case_types
    - library_names
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - always_use_package_imports: true
    -  avoid_empty_else: true
    - unnecessary_brace_in_string_interps
    - avoid_redundant_argument_values
    - leading_newlines_in_multiline_strings
    - lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures
    - slash_for_doc_comments